In [ ]:
!pip install Twython
import pandas as pd
import numpy as np 
from twython import Twython

CONSUMER_KEY = "zJqvZslXaZsCXGE8pjXxghI0Z"
CONSUMER_SECRET = "08W0dMtVqNRtJ3J7S9SGyvhrnoCC2dmpDFgOZscdgDmFt81Gsm"
OAUTH_TOKEN = "1530236331921653760-Vh7uPCVtmpydrbcAG2EO9i4GCmKq0a"
OAUTH_TOKEN_SECRET = "LWnoFmdsPcPDTXDM8o6gNRklQ98RFPM5lGquwcFLrW47C"
twitter = Twython(
    CONSUMER_KEY, CONSUMER_SECRET,
    OAUTH_TOKEN, OAUTH_TOKEN_SECRET)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting Twython
  Downloading twython-3.9.1-py3-none-any.whl (33 kB)
Requirement already satisfied: requests>=2.1.0 in /usr/local/lib/python3.7/dist-packages (from Twython) (2.23.0)
Requirement already satisfied: requests-oauthlib>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from Twython) (1.3.1)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->Twython) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->Twython) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->Twython) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.1.0->Twython) (2022.6.15)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.4.0->Twython) (3.2.0)
Installing collected packages: Twython
Successfully installed Twython-3.9.1

## Στις 19/6 τράβηξα 10.000 tweets με τα key words "Ουκρανία" και "πόλεμος". Η αναζήτηση έφτασε μέχρι τις 10/6. Γι' αυτό στις 22/6 τράβηξα 3.000 ακόμα tweets με το ίδιο θέμα, ώστε τα δεδομένα μου να καλύπτουν τουλάχιστον ένα 10ήμερο, και στη συνέχεια έκανα merge τα dataframes. 
**Ο κώδικας με τη λίστα "tweets" εξαιτίας του μεγάλου αριθμού tweets (10.000) κάποιες φορές δεν τρέχει. Το "tweets2", παρακάτω, τρέχει κανονικά.*

In [ ]:
tweets = []
MAX_ATTEMPTS = 100
COUNT_OF_TWEETS_TO_BE_FETCHED = 10000 

for i in range(0,MAX_ATTEMPTS):
  if(COUNT_OF_TWEETS_TO_BE_FETCHED < len(tweets)):
    print("We Got ", len(tweets), " tweets!!!")
    break 
  if(0 == i):
    results = twitter.search(q=("ουκρανία-filter:retweets"or"ουκρανια-filter:retweets"or"πόλεμος-filter:retweets" or "πολεμος-filter:retweets") , lang= 'el' , count='100')
    
    print("I Got:", len(results['statuses']), " tweets")
  else:
    results = twitter.search(q=("ουκρανία-filter:retweets"or"ουκρανια-filter:retweets"or"πόλεμος-filter:retweets" or "πολεμος-filter:retweets") , lang= 'el' , count='100', include_entities='true',max_id=next_max_id)
    
    print("I Got:", len(results['statuses']), " tweets")

  for result in results['statuses']:
    tweets.append(result)

  try:
    next_results_url_params = results['search_metadata']['next_results']
    next_max_id = next_results_url_params.split('max_id=')[1].split('&')[0]
  except:
    break

I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets

In [ ]:
len(tweets)

10000

In [ ]:
tweets_df = pd.DataFrame(tweets)
tweets_df.tail(2)

,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,in_reply_to_status_id_str,...,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,extended_entities,quoted_status_id,quoted_status_id_str,quoted_status
9998,Fri Jun 10 18:51:19 +0000 2022,1535333805711663104,1535333805711663104,Εάν πραγματικά θέλεις να καταλάβεις τι και για...,True,"{'hashtags': [{'text': 'Ουκρανια', 'indices': ...","{'iso_language_code': 'el', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",NaN,None,...,1,1,False,False,False,el,NaN,NaN,NaN,NaN
9999,Fri Jun 10 18:50:50 +0000 2022,1535333686064947201,1535333686064947201,Τεράστια ανταπόκριση στο κάλεσμα ανθρωπιστικής...,True,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'iso_language_code': 'el', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",NaN,None,...,0,0,False,False,False,el,NaN,NaN,NaN,NaN

In [ ]:
#tweets2_df = pd.DataFrame(tweets2)

In [ ]:
#tweets2_df.tail(2)

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
tweets_df.to_csv("/content/gdrive/My Drive/Colab Notebooks/tweets_ukraine.tsv", sep='\t')

In [ ]:
ukrainetweets = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/tweets_ukraine.tsv", sep='\t')
ukrainetweets.head(1)

,Unnamed: 0,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,extended_entities,quoted_status_id,quoted_status_id_str,quoted_status
0,0,Sun Jun 19 12:17:02 +0000 2022,1538496073328730112,1538496073328730112,Ρωσία: H επίθεση στην ανατολική Ουκρανία εξελί...,False,"{'hashtags': [{'text': 'Επικαιρότητα', 'indice...","{'iso_language_code': 'el', 'result_type': 're...","<a href=""http://www.wpautopublish.com"" rel=""no...",NaN,...,0,0,False,False,False,el,NaN,NaN,NaN,NaN

In [ ]:
tweets2 = []
MAX_ATTEMPTS = 100
COUNT_OF_TWEETS_TO_BE_FETCHED = 3000 

for i in range(0,MAX_ATTEMPTS):
  if(COUNT_OF_TWEETS_TO_BE_FETCHED < len(tweets2)):
    print("We Got ", len(tweets2), " tweets!!!")
    break 
  if(0 == i):
    results = twitter.search(q=("ουκρανία-filter:retweets"or"ουκρανια-filter:retweets"or"πόλεμος-filter:retweets" or "πολεμος-filter:retweets") , lang= 'el' , count='100')
    
    print("I Got:", len(results['statuses']), " tweets")
  else:
    results = twitter.search(q=("ουκρανία-filter:retweets"or"ουκρανια-filter:retweets"or"πόλεμος-filter:retweets" or "πολεμος-filter:retweets") , lang= 'el' , count='100', include_entities='true',max_id=next_max_id)
    
    print("I Got:", len(results['statuses']), " tweets")

  for result in results['statuses']:
    tweets2.append(result)

  try:
    next_results_url_params = results['search_metadata']['next_results']
    next_max_id = next_results_url_params.split('max_id=')[1].split('&')[0]
  except:
    break

I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
I Got: 100  tweets
We Got  3100  tweets!!!

In [ ]:
len(tweets2)

3100

In [ ]:
tweets2_df = pd.DataFrame(tweets2)
tweets2_df.head(2)

,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,in_reply_to_status_id_str,...,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,quoted_status_id,quoted_status_id_str,quoted_status,extended_entities
0,Wed Jun 22 09:41:43 +0000 2022,1539544151653552128,1539544151653552128,"Ουκρανία: Εκτεταμένοι ρωσικοί βομβαρδισμοί, αλ...",False,"{'hashtags': [{'text': 'Ουκρανία', 'indices': ...","{'iso_language_code': 'el', 'result_type': 're...","<a href=""https://www.hootsuite.com"" rel=""nofol...",NaN,None,...,0,0,False,False,False,el,NaN,NaN,NaN,NaN
1,Wed Jun 22 09:39:56 +0000 2022,1539543700287758337,1539543700287758337,Θα αποσύρει τους τενεκέδες τους από την Ουκραν...,True,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'iso_language_code': 'el', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",NaN,None,...,0,0,False,False,False,el,1.539542e+18,1539542269333757954,{'created_at': 'Wed Jun 22 09:34:14 +0000 2022...,NaN

In [ ]:
tweets2_df.to_csv("/content/gdrive/My Drive/Colab Notebooks/tweets2_ukraine.tsv", sep='\t')

In [ ]:
ukrainetweets2 = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/tweets2_ukraine.tsv", sep='\t')
ukrainetweets2.tail(1)

,Unnamed: 0,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,quoted_status_id,quoted_status_id_str,quoted_status,extended_entities
3099,3099,Sun Jun 19 08:16:02 +0000 2022,1538435423688699904,1538435423688699904,Ουκρανία: Ρωσικό πλήγμα σε αποθήκη καυσίμων ...,False,"{'hashtags': [{'text': 'Επικαιρότητα', 'indice...","{'iso_language_code': 'el', 'result_type': 're...","<a href=""http://www.wpautopublish.com"" rel=""no...",NaN,...,0,0,False,False,False,el,NaN,NaN,NaN,NaN

In [ ]:
df_ukrainetweets=pd.concat([ukrainetweets, ukrainetweets2], axis="rows")
df_ukrainetweets.head(2)

,Unnamed: 0,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,extended_entities,quoted_status_id,quoted_status_id_str,quoted_status
0,0,Sun Jun 19 12:17:02 +0000 2022,1538496073328730112,1538496073328730112,Ρωσία: H επίθεση στην ανατολική Ουκρανία εξελί...,False,"{'hashtags': [{'text': 'Επικαιρότητα', 'indice...","{'iso_language_code': 'el', 'result_type': 're...","<a href=""http://www.wpautopublish.com"" rel=""no...",NaN,...,0,0,False,False,False,el,NaN,NaN,NaN,NaN
1,1,Sun Jun 19 12:16:15 +0000 2022,1538495877987409921,1538495877987409921,Ρωσία: Το υπουργείο Άμυνας δηλώνει ότι η επίθε...,False,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'iso_language_code': 'el', 'result_type': 're...","<a href=""https://contentstudio.io"" rel=""nofoll...",NaN,...,0,0,False,False,False,el,NaN,NaN,NaN,NaN

In [ ]:
df_ukrainetweets.tail(2)

,Unnamed: 0,created_at,id,id_str,text,truncated,entities,metadata,source,in_reply_to_status_id,...,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,extended_entities,quoted_status_id,quoted_status_id_str,quoted_status
3098,3098,Sun Jun 19 08:16:28 +0000 2022,1538435531104784384,1538435531104784384,"Arno Klarsfeld, ο δικηγόρος του Συνδέσμου Γιων...",True,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'iso_language_code': 'el', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",NaN,...,0,0,False,False,NaN,el,NaN,NaN,NaN,NaN
3099,3099,Sun Jun 19 08:16:02 +0000 2022,1538435423688699904,1538435423688699904,Ουκρανία: Ρωσικό πλήγμα σε αποθήκη καυσίμων ...,False,"{'hashtags': [{'text': 'Επικαιρότητα', 'indice...","{'iso_language_code': 'el', 'result_type': 're...","<a href=""http://www.wpautopublish.com"" rel=""no...",NaN,...,0,0,False,False,False,el,NaN,NaN,NaN,NaN

In [ ]:
df_ukrainetweets.to_csv("/content/gdrive/My Drive/Colab Notebooks/twitter_ukraine.tsv", sep='\t')